Update checkTestClasses.yml for Azure Pipelines

diff --git a/pipelines/checkTestClasses.yml b/pipelines/checkTestClasses.yml
--- a/pipelines/checkTestClasses.yml
+++ b/pipelines/checkTestClasses.yml
@@ -53,18 +53,18 @@ jobs:
           env:
               BRANCH_NAME: $(Build.SourceBranchName)
               SYSTEM_ACCESSTOKEN: $(System.AccessToken)
-        # - script: |
-        #     if ! command -v sfdx &> /dev/null
-        #       then
-        #           echo "SFDX Not found, installing..."
-        #           npm install -g @salesforce/cli --loglevel verbose
-        #         #   echo y | sf plugins install sfdx-git-delta
-        #           # echo y | sfdx plugins:install @salesforce/sfdx-scanner
-        #         #   sf plugins install @salesforce/sfdx-scanner
-        #       else
-        #           echo "SFDX installed."
-        #     fi
-        #   displayName: "Install SFDX and SDG"
+        - script: |
+            if ! command -v sfdx &> /dev/null
+              then
+                  echo "SFDX Not found, installing..."
+                  npm install -g @salesforce/cli --loglevel verbose
+                #   echo y | sf plugins install sfdx-git-delta
+                  # echo y | sfdx plugins:install @salesforce/sfdx-scanner
+                #   sf plugins install @salesforce/sfdx-scanner
+              else
+                  echo "SFDX installed."
+            fi
+          displayName: "Install SFDX and SDG"
 
 
         - task: Bash@3
@@ -78,6 +78,7 @@ jobs:
                 class=$(echo "$line" | sed 's/[,[:space:]]*$//')
                   if [ -n "$class" ]; then
                     echo "Test Class: $class"
+                    output=$(ssf apex run test --class-names ""$class""  --result-format human  --synchronous)
                   fi
                 
               done < "$file"
