Set up CI with Azure Pipelines
[skip ci]

diff --git a/pipelines/checkTestClasses.yml b/pipelines/checkTestClasses.yml
--- a/pipelines/checkTestClasses.yml
+++ b/pipelines/checkTestClasses.yml
@@ -1,1 +1,85 @@
+# Starter pipeline
+# Start with a minimal pipeline that you can customize to build and deploy your code.
+# Add steps that build, run tests, deploy, and more:
+# https://aka.ms/yaml
+
+
 trigger : none
+
+
+jobs:
+- deployment: ValidateAndDeployment
+  displayName: Validate and deployment
+  pool:
+    vmImage: ubuntu-latest
+  environment: 
+   name: $(environmentName)
+  strategy:
+    runOnce:
+      deploy:
+        steps:
+        - checkout: self
+          clean: true
+          fetchDepth: full
+          persistCredentials: true
+        - task: NodeTool@0 
+          inputs:
+            versionSpec: '20.x'
+        - task: DownloadSecureFile@1
+          name: SalesforceToken
+          displayName: 'Download auth file for SFDX'
+          inputs:
+            secureFile: $(environmentName)Token.json
+        # - script: |
+        #     echo "*******SOURCE_BRANCH_NAME****************"
+        #     sourceBranch=$(echo "prj/""$BRANCH_NAME" | sed 's|refs/heads/||g')
+        #     echo "##vso[task.setvariable variable=sourceBranch;]$sourceBranch"
+        #     echo "$sourceBranch"
+        #     echo "*****************************************"
+        #     curl -H "Authorization: Bearer $SYSTEM_ACCESSTOKEN" -X GET -L "https://dev.azure.com/suvam1999roy/Azure%20Devops%20Test/_apis/build/latest/$(System.DefinitionId)?branchName=$sourceBranch&api-version=7.0-preview.1" -o sourceVersionResponse.json
+        #     echo "************************"
+        #     cat sourceVersionResponse.json
+        #     echo "************************"
+        #     if cat sourceVersionResponse.json | grep -o '"result":"[^"]*' | grep -o '[^"]*$' | grep -q succeeded; then
+        #       latestBuildCommit=$(cat sourceVersionResponse.json | grep -o '"sourceVersion":"[^"]*' | grep -o '[^"]*$')
+        #       echo "Last build succeeded, commit set to latest deployed to environment: $latestBuildCommit"
+        #       echo "##vso[task.setvariable variable=latestBuildCommit]$latestBuildCommit"
+        #     else
+        #       latestBuildCommit=$(commitID)
+        #       echo "Last build failed or error, commit set to initial one from branch $BRANCH_NAME and its $latestBuildCommit"
+        #       echo "##vso[task.setvariable variable=latestBuildCommit]$latestBuildCommit"
+        #     fi
+        #   displayName: "Download latest build commit for environment"
+          env:
+              BRANCH_NAME: $(Build.SourceBranchName)
+              SYSTEM_ACCESSTOKEN: $(System.AccessToken)
+        - script: |
+            if ! command -v sfdx &> /dev/null
+              then
+                  echo "SFDX Not found, installing..."
+                  npm install -g @salesforce/cli --loglevel verbose
+                #   echo y | sf plugins install sfdx-git-delta
+                  # echo y | sfdx plugins:install @salesforce/sfdx-scanner
+                #   sf plugins install @salesforce/sfdx-scanner
+              else
+                  echo "SFDX installed."
+            fi
+          displayName: "Install SFDX and SDG"
+
+
+        - task: Bash@3
+          displayName: 'Run Apex Tests from File and Validate Pass Rate'
+          inputs:
+            targetType: 'inline'
+            script: |
+              set -e
+              
+              failed=0
+              file="allTestclasses.txt"
+
+              while IFS=, read -r line; do
+                for word in $(echo $line | tr -s ' ,' '\n'); do
+                  echo $word
+
+                done
+              done < "$file"
