Update checkTestClasses.yml for Azure Pipelines

diff --git a/pipelines/checkTestClasses.yml b/pipelines/checkTestClasses.yml
--- a/pipelines/checkTestClasses.yml
+++ b/pipelines/checkTestClasses.yml
@@ -53,24 +53,23 @@ jobs:
           env:
               BRANCH_NAME: $(Build.SourceBranchName)
               SYSTEM_ACCESSTOKEN: $(System.AccessToken)
-        - script: |
-            if ! command -v sfdx &> /dev/null
-              then
-                  echo "SFDX Not found, installing..."
-                  npm install -g @salesforce/cli --loglevel verbose
-                #   echo y | sf plugins install sfdx-git-delta
-                  # echo y | sfdx plugins:install @salesforce/sfdx-scanner
-                #   sf plugins install @salesforce/sfdx-scanner
-              else
-                  echo "SFDX installed."
-            fi
-          displayName: "Install SFDX and SDG"
+        # - script: |
+        #     if ! command -v sfdx &> /dev/null
+        #       then
+        #           echo "SFDX Not found, installing..."
+        #           npm install -g @salesforce/cli --loglevel verbose
+        #         #   echo y | sf plugins install sfdx-git-delta
+        #           # echo y | sfdx plugins:install @salesforce/sfdx-scanner
+        #         #   sf plugins install @salesforce/sfdx-scanner
+        #       else
+        #           echo "SFDX installed."
+        #     fi
+        #   displayName: "Install SFDX and SDG"
 
 
         - task: Bash@3
           displayName: 'Run Apex Tests from File and Validate Pass Rate'
           inputs:
-            targetType: 'inline'
             script: |
 
               file="allTestclasses.txt"
@@ -78,6 +77,5 @@ jobs:
               while IFS=, read -r line; do
                 for word in $(echo $line | tr -s ',' '\n'); do
                   echo $word
-
                 done
               done < "$file"
