Update deploy changes after pr mergered updated.yml for Azure Pipelines

diff --git a/pipelines/deploy changes after pr mergered updated.yml b/pipelines/deploy changes after pr mergered updated.yml
--- a/pipelines/deploy changes after pr mergered updated.yml
+++ b/pipelines/deploy changes after pr mergered updated.yml
@@ -98,12 +98,12 @@ jobs:
         - script: |
             if [ $(runTestClasses) = "true" ]; then
               echo "runTestClasses variable set to true, running build with test classes"
-              sfdx force:source:deploy -l RunLocalTests  -x manifest/package.xml --targetusername $(environmentName) 
-              sfdx apex run test --code-coverage  -l RunLocalTests -r human --target-org $(environmentName) --synchronous
+              sfdx force:source:deploy -l RunSpecifiedTests -r WelcomeToPwCTest,WelcomeQATest  -x manifest/package.xml --targetusername $(environmentName) 
+              # sfdx apex run test --code-coverage  -l RunLocalTests -r human --target-org $(environmentName) --synchronous
                # Run Salesforce tests and extract code coverage percentage
-              coverage_output=$(sfdx apex run test --code-coverage  -l RunLocalTests -r human --target-org $(environmentName) --synchronous)
-              # coverage_percentage=$(echo "$coverage_output" | grep -oP '\d+%')
-              echo "-----------code coverage: $coverage_output"
+              # coverage_output=$(sfdx apex run test --code-coverage  -l RunLocalTests -r human --target-org $(environmentName) --synchronous)
+              # # coverage_percentage=$(echo "$coverage_output" | grep -oP '\d+%')
+              # echo "-----------code coverage: $coverage_output"
               # percentages=$(echo "$coverage_output" | awk 'CLASSES')
               # echo "-----------code coverage: $percentages"
               # # Iterate through percentages and check if any is below 90%
@@ -114,34 +114,34 @@ jobs:
               #     fi
               # done <<< "$percentages"
 
-               IFS=$'\n' read -r -a lines <<< "$coverage_output"
-                classes=()
-                percentages=()
+              #  IFS=$'\n' read -r -a lines <<< "$coverage_output"
+              #   classes=()
+              #   percentages=()
 
-                # Loop through each line of coverage_output to find "CLASSES" and "PERCENTAGES" columns
-                for line in "${lines[@]}"; do
-                    if [[ "$line" =~ ^CLASSES: ]]; then
-                        IFS=' ' read -r -a classes <<< "${line#*:}"
-                    elif [[ "$line" =~ ^PERCENTAGES: ]]; then
-                        IFS=' ' read -r -a percentages <<< "${line#*:}"
-                    fi
-                done
+              #   # Loop through each line of coverage_output to find "CLASSES" and "PERCENTAGES" columns
+              #   for line in "${lines[@]}"; do
+              #       if [[ "$line" =~ ^CLASSES: ]]; then
+              #           IFS=' ' read -r -a classes <<< "${line#*:}"
+              #       elif [[ "$line" =~ ^PERCENTAGES: ]]; then
+              #           IFS=' ' read -r -a percentages <<< "${line#*:}"
+              #       fi
+              #   done
 
-                # Loop through classes and percentages to check if any class has coverage below 90%
-                failed=false
-                for ((i=0; i<${#classes[@]}; i++)); do
-                    class="${classes[i]}"
-                    percentage="${percentages[i]}"
-                    if (( $(echo "$percentage < 90" | bc -l) )); then
-                        echo "Code coverage for $class is below 90% ($percentage%)"
-                        failed=true
-                    fi
-                done
+              #   # Loop through classes and percentages to check if any class has coverage below 90%
+              #   failed=false
+              #   for ((i=0; i<${#classes[@]}; i++)); do
+              #       class="${classes[i]}"
+              #       percentage="${percentages[i]}"
+              #       if (( $(echo "$percentage < 90" | bc -l) )); then
+              #           echo "Code coverage for $class is below 90% ($percentage%)"
+              #           failed=true
+              #       fi
+              #   done
 
-                # Fail the pipeline if any class has coverage below 90%
-                if [ "$failed" = true ]; then
-                    exit 1
-                fi
+              #   # Fail the pipeline if any class has coverage below 90%
+              #   if [ "$failed" = true ]; then
+              #       exit 1
+              #   fi
 
               # echo "All code coverage percentages are 90% or above."
               # exit 0  # Exit with success code
