Update deploy changes after pr mergered updated.yml for Azure Pipelines

diff --git a/pipelines/deploy changes after pr mergered updated.yml b/pipelines/deploy changes after pr mergered updated.yml
--- a/pipelines/deploy changes after pr mergered updated.yml
+++ b/pipelines/deploy changes after pr mergered updated.yml
@@ -99,7 +99,18 @@ jobs:
             if [ $(runTestClasses) = "true" ]; then
               echo "runTestClasses variable set to true, running build with test classes"
               sfdx force:source:deploy -l RunLocalTests  -x manifest/package.xml --targetusername $(environmentName) 
-              sfdx apex run test --code-coverage  -l RunLocalTests -r human --target-org $(environmentName) --synchronous
+              # sfdx apex run test --code-coverage  -l RunLocalTests -r human --target-org $(environmentName) --synchronous
+               # Run Salesforce tests and extract code coverage percentage
+              coverage_output=$(sfdx apex run test --code-coverage  -l RunLocalTests -r human --target-org $(environmentName) --synchronous)
+              # coverage_percentage=$(echo "$coverage_output" | grep -oP '\d+%')
+              echo "-----------code coverage: $coverage_output"
+
+              # Fail the build if coverage is below 90%
+              # if [ "${coverage_percentage%\%}" -lt 90 ]; then
+              #   echo "Code coverage is below 90%. Failing the build."
+              #   exit 1
+              # fi
+
             else
               sfdx force:source:deploy -x manifest/package.xml --targetusername $(environmentName)
             fi
